version: '3.8'

services:
  tech_radar:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
      - "3001:3001"
    tty: true
    stdin_open: true
    volumes:
      - ./docs:/app
    command: ["browser-sync", "start", "--watch" , "**/*",  "--server",  "/app"]
